# Influx OSS API Service
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 2.0.0
#
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Ready
#'
#' @description Ready Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field status  character [optional]
#'
#' @field started  character [optional]
#'
#' @field up  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Ready <- R6::R6Class(
  'Ready',
  public = list(
    `status` = NULL,
    `started` = NULL,
    `up` = NULL,
    initialize = function(
        `status`=NULL, `started`=NULL, `up`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!is.null(`started`)) {
        stopifnot(is.character(`started`), length(`started`) == 1)
        self$`started` <- `started`
      }
      if (!is.null(`up`)) {
        stopifnot(is.character(`up`), length(`up`) == 1)
        self$`up` <- `up`
      }
    },
    toJSON = function() {
      ReadyObject <- list()
      if (!is.null(self$`status`)) {
        ReadyObject[['status']] <-
          self$`status`
      }
      if (!is.null(self$`started`)) {
        ReadyObject[['started']] <-
          self$`started`
      }
      if (!is.null(self$`up`)) {
        ReadyObject[['up']] <-
          self$`up`
      }

      ReadyObject
    },
    fromJSON = function(ReadyJson) {
      ReadyObject <- jsonlite::fromJSON(ReadyJson)
      if (!is.null(ReadyObject$`status`)) {
        self$`status` <- ReadyObject$`status`
      }
      if (!is.null(ReadyObject$`started`)) {
        self$`started` <- ReadyObject$`started`
      }
      if (!is.null(ReadyObject$`up`)) {
        self$`up` <- ReadyObject$`up`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          "%s"
                ',
        self$`status`
        )},
        if (!is.null(self$`started`)) {
        sprintf(
        '"started":
          "%s"
                ',
        self$`started`
        )},
        if (!is.null(self$`up`)) {
        sprintf(
        '"up":
          "%s"
                ',
        self$`up`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ReadyJson) {
      ReadyObject <- jsonlite::fromJSON(ReadyJson)
      self$`status` <- ReadyObject$`status`
      self$`started` <- ReadyObject$`started`
      self$`up` <- ReadyObject$`up`
      self
    }
  )
)

